---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busapp
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bus
      tier: frontend
  template:
    metadata:
      labels:
        app: bus
        tier: frontend
    spec:
      containers:
        - name: busapp
          image: learnitguide/busapp:1.0
          ports:
            - containerPort: 8001


---
apiVersion: v1
kind: Service
metadata:
  name: busapp
  namespace: default
spec:
  selector:
    app: bus
    tier: frontend

  ports:
    - port: 80
      targetPort: 8001
  type: LoadBalancer
